version: '3'

services:
  app:
    build: .
    working_dir: /example
    command: python ./example_project/manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONBUFFERED=True
      - DATABASE_URL=postgres://postgres@db/postgres
      - DJANGO_SETTINGS_MODULE=data_federation_ingest.settings
      - DEBUG=TRUE
    stdin_open: true
    tty: true
    volumes:
      - .:/example
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
